In [19]:
import random
s=[]
for i in range(100):
    s.append(random.randint(1,100))
su=sum(s)
print(s,end="")
print(su)
avg=
    

TypeError: 'int' object is not callable

In [6]:
#q1
import random

def sumavg(a):
    s=sum(a)
    av=s/len(a)
    print("\nthe sum & avg is",s,av)
    
a = [random.randint(1,100) for i in range(100)]
for i in a:
    print(i,end=" ")
sumavg(a)



    
     

37 65 47 84 84 17 9 39 19 14 1 21 29 82 26 18 57 57 77 95 91 23 49 52 57 33 65 62 34 4 82 100 11 42 75 99 72 90 13 39 98 83 97 41 39 31 82 51 66 39 89 83 36 34 9 9 67 38 14 43 30 51 84 44 36 52 94 9 88 85 33 23 97 4 8 29 57 30 85 91 37 75 38 41 42 94 24 92 95 99 76 61 30 77 11 62 32 72 47 27 
the sum & avg is 5182 51.82


In [4]:
#q2
def rotate(arg1, arg2, arg3):
    return (arg3, arg1, arg2)

a, b, c = 'Doug', 22, 1984

# Call the function three times and unpack the result into a, b, and c each time
for _ in range(3):
    a, b, c = rotate(a, b, c)
    print(a, b, c)


1984 Doug 22
22 1984 Doug
Doug 22 1984


In [21]:
#q3
def createlist(l):
    b=int(input("enter element"))
    l.append(b)
    return l
def insertelement(l):
    a=int(input("enter the element:"))
    b=int(input("enter the position"))
    l.insert(b,a)
def delete(l):
    a=int(input("enter the position to be deleted"))
    l.pop(a)
    




print("a--> enter the elements")
print("b->display")
print("c->insert at specific position")
print("d->delete at specific position")
l=[]
while True:
    choise=input("enter a,b ,c or d: ")
    if(choise=='a'):
      l=createlist(l)
    elif(choise=='b'):
        print(l)
    elif(choise=='c'):
        insertelement(l)
    elif(choise=='d'):
        delete(l)
    else:
        print("exiting")
        break;
        
    
    

print(l)


      

a--> enter the elements
b->display
c->insert at specific position
d->delete at specific position


enter a,b ,c or d:  a
enter element 334
enter a,b ,c or d:  b


[334]


enter a,b ,c or d:  c
enter the element: 67
enter the position 1
enter a,b ,c or d:  b


[334, 67]


enter a,b ,c or d:  c
enter the element: 1
enter the position b


ValueError: invalid literal for int() with base 10: 'b'

In [80]:
#q4

l=[2,1,2,3,4,4,4,5,88,77,5,5,77]
s=[]
a=int(input("enter the element to remove all occurance of it:"))
for i in l:
    if a!=i :
        s.append(i)
print(s)
    
    

enter the element to remove all occurance of it: 77


[2, 1, 2, 3, 4, 4, 4, 5, 88, 5, 5]


In [118]:
#basis
"""
a=(1,2,3,4) #as tuple are immutable so it cant be changed it will show error
a.append(2) # but tuple can be added with tuple ex-(1,2)+(3,4)
print(a)
"""
a=[1,2,3,4] #as list are mutable so it will not show error
a.append(2)
print(a)

s="siva"  # strings are immutable they cant be changed
s[1]


[1, 2, 3, 4, 2]


'i'

In [168]:
#basis

a=(1,2,3)+(8,9)# +("siva") it is not allowed to add string to int
print(a)
d=[1,2,3]+[8,9]+["siva"]
print(d)
e=('s','i')+('v','k')
print(e)
f=['s','i']+['v']
print(f)



(1, 2, 3, 8, 9)
[1, 2, 3, 8, 9, 'siva']
('s', 'i', 'v', 'k')


TypeError: can only concatenate list (not "str") to list

In [172]:
#h)
x=7
del x
print(x)


NameError: name 'x' is not defined

In [174]:
# i)
numbers = [1, 2, 3, 4, 5]
 numbers.index(10)

ValueError: 10 is not in list

In [230]:
 n = [1, 2, 3, 4, 5]
 n.extend([6,7,8])
print(n)                 #difference btw append & extend
d=[1, 2, 3, 4, 5]
d.append(6)
d.append([8,9,7,9])
print(d)


[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, [8, 9, 7, 9]]


In [252]:
#6)
a=[1,2,3,4,5,6,2,2,2]
n=int(input("enter the number to be searched in the list"))
sum=0
if n in a:
    print("yes it is present")
    for i in range(len(a)):
        if n==a[i]:
            sum=sum+1
        
        
    print(sum)
else:
    print("not there in the list")


enter the number to be searched in the list 2


yes it is present
4


In [262]:
#q7)

a=[1,3,5,6]
b=[]
sum=0
for i in range(len(a)):
    sum=sum+a[i]
    b.append(sum)
print(b)

[1, 4, 9, 15]


In [284]:
n=int(input("enter the no: "))
for i in range(1,n+1):
      print("multiples of",i,"are :",end=" " )
      for j in range(1,6):
          print(i*j, end=" " )
      print()


enter the no:  9


multiples of 1 are : 1 2 3 4 5 
multiples of 2 are : 2 4 6 8 10 
multiples of 3 are : 3 6 9 12 15 
multiples of 4 are : 4 8 12 16 20 
multiples of 5 are : 5 10 15 20 25 
multiples of 6 are : 6 12 18 24 30 
multiples of 7 are : 7 14 21 28 35 
multiples of 8 are : 8 16 24 32 40 
multiples of 9 are : 9 18 27 36 45 


In [316]:
 address='B-6,Lodhiroad,Delhi'
 list1=[1,2,3]
 list2=['a',1,'z',26,'d',4]
 tuple1=('a','e','i','o','u')
 tuple2=([2,4,6,8],[3,6,9],[4,8],5)
 print(list1*2)
 print(min(list1))
 print(max(list1))
  


[1, 2, 3, 1, 2, 3]
1
3


In [320]:
s = ((1, 2, 'a'), (3, 4, 'b'), (5, 6, 7))
s[0][0]

1

In [361]:
#q10)
def tot(x):
    sum=0
    for i in x:
        for j in i:
           if isinstance(j,(int,float)):
             sum=sum+j
    print(sum)

x=((1, 2, 'a'), (3, 4, 'b'), (5, 6, 7))
tot(x)
 

28


In [414]:

#q11)
r=int(input("enter the number of rows"))
c=int(input("enter the number of columns"))


co=[]

for i in range(r):
    ro=[]
    s=input("enter the row element").split()
    for j in s:
       ro.append(int(j))
    co.append(ro)
print(co)

for i in co:
    for j in i:
        print("%4d"% j , end=" ")
    print()


 


enter the number of rows 3
enter the number of columns 3
enter the row element 1 44 3
enter the row element 2
enter the row element 4 6 77


[[1, 44, 3], [2], [4, 6, 77]]
   1   44    3 
   2 
   4    6   77 


In [418]:
#q12)
def column_sum(matrix, col_index):
    total = 0
    for row in matrix:
        total += row[col_index]
    return total

# Main program
rows, columns = 3, 4
matrix = []

print("Enter a 3-by-4 matrix row by row:")

for _ in range(rows):
    row = input().split()
    row = [float(num) for num in row]  # Convert each element to float
    matrix.append(row)

print("\nMatrix:")
for row in matrix:
    print(row)

print("\nSum of each column:")
for col in range(columns):
    print(f"Sum of column {col}: {column_sum(matrix, col)}")



Enter a 3-by-4 matrix row by row:


 2 2
 22 22
 3 3



Matrix:
[2.0, 2.0]
[22.0, 22.0]
[3.0, 3.0]

Sum of each column:
Sum of column 0: 27.0
Sum of column 1: 27.0


IndexError: list index out of range

In [420]:
#q13)
tuples_list = [(1, 3), (3, 2), (2, 1), (4, 4)]
sorted_tuples = sorted(tuples_list, key=lambda x: x[1])
print(sorted_tuples)  # Output: [(2, 1), (3, 2), (1, 3), (4, 4)]


[(2, 1), (3, 2), (1, 3), (4, 4)]


In [469]:
#q14)
su=[i**2 for i in range(11) ]
print(su)


su = [i for i in range(11) if i%2==0] 
print(su)
su = [i/2 for i in range(11) if i%2==0] 
print(su)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[0, 2, 4, 6, 8, 10]
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0]


In [440]:
s=[]
for i in range(11):
    i=i**2
    s.append(i)
print(s)
    


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [477]:
matrix=[]
for i in range(4):
    row=input().split()
    row=[int(i) for i in row]
    matrix.append(row)
print(matrix)

 2 2 12 2
 3 3 3 3
 2 2 2 2
 3 4 5 5


[[2, 2, 12, 2], [3, 3, 3, 3], [2, 2, 2, 2], [3, 4, 5, 5]]


In [486]:
#Q17) correct code
import math

def calculate_mean(numbers):
    return sum(numbers) / len(numbers)

def calculate_std_deviation(numbers, mean):
    variance = sum((x - mean) ** 2 for x in numbers) / (len(numbers) - 1)
    return math.sqrt(variance)

# Prompt the user to enter ten numbers
numbers = []
print("Enter ten numbers:")
for _ in range(10):
    number = float(input())
    numbers.append(number)

# Calculate mean
mean = calculate_mean(numbers)

# Calculate standard deviation
std_deviation = calculate_std_deviation(numbers, mean)

# Display results
print(f"The mean is {mean:.2f}")
print(f"The standard deviation is {std_deviation:.5f}")


Enter ten numbers:


 2
 2
 2
 2
 2
 2
 2
 2
 2
 2


TypeError: 'int' object is not callable

In [488]:
#q18)
# Original list
original_list = [1, 2, 3, 4, 5]

# New list with squares of every element
squared_list = [x**2 for x in original_list]

# Print the new list
print(squared_list)


[1, 4, 9, 16, 25]


In [542]:
#q1)
import numpy as np
a=np.array([[1,1,1],[1,1,1]])
print(a)
b=np.zeros((3,3))
print(b)
c=np.full((2,5),7)
print(c)







[[1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [558]:
#q2)
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("original aarray:",a)
cube=np.power(a,3)
print("cube is:",cube)
sum=a+7
print("sum of 7 is:",sum)
mul=a*2
print("mul of 2 is:",mul)


original aarray: [[1 2 3]
 [4 5 6]]
cube is: [[  1   8  27]
 [ 64 125 216]]
sum of 7 is: [[ 8  9 10]
 [11 12 13]]
mul of 2 is: [[ 2  4  6]
 [ 8 10 12]]


In [596]:
#q3)
import numpy as np
x=np.arange(2,19,2)
y=x.reshape(3,3)
print(y)
a=np.arange(9,0,-1)
b=a.reshape(3,3)
print(b)
mul=np.multiply(y,b)
print(mul)




[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[18 32 42]
 [48 50 48]
 [42 32 18]]


In [598]:
#q4)

import numpy as np

# Create a 2x2 array
array = np.array([[1, 2], [3, 4]])

print("Original array:")
print(array)

# Swap the first row (no change since there are only two rows, but let's do it for consistency)
array[[0, 1]] = array[[1, 0]]

print("\nArray after swapping rows:")
print(array)

# Swap the first two columns
array[:, [0, 1]] = array[:, [1, 0]]

print("\nArray after swapping columns:")
print(array)



Original array:
[[1 2]
 [3 4]]

Array after swapping rows:
[[3 4]
 [1 2]]

Array after swapping columns:
[[4 3]
 [2 1]]


In [612]:
#q5)
import numpy as np

l1=[2,3,5,7,11]
l2=[13,17,19,23,29]
array=np.array([l1,l2])
array

array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29]])

In [628]:
#q6))
import numpy as np
a=np.array([[2**0,2**1,2**2],[2**3,2**4,2**5]])
b=a.flatten()
c=a.ravel()#in ravel if u modify some thing it will also grt modify in the orginal array ex- in a 
c[0]=99

print(a)
print(b)
print(c)
print(a)




[[99  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]
[99  2  4  8 16 32]
[[99  2  4]
 [ 8 16 32]]


In [632]:
#q7)
import numpy as np
from collections import Counter

# Example array
array = np.array([1, 2, 3, 4, 2, 4, 3, 4, 4])

# Count the frequency of each element
frequency = Counter(array)

# Find the most frequent value
most = frequency.most_common(1)[0][0]
print("Most frequent value:", most)


Most frequent value: [(4, 4), (2, 2), (3, 2), (1, 1)]


In [660]:
#Q8)
import numpy as np
a=np.linspace(1.1,6.6,6)
b=a.reshape(2,3)
c=b.astype(int)
print(a)
print(b)
print(c)

[1.1 2.2 3.3 4.4 5.5 6.6]
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]
