In [9]:
#q1)
import numpy as np
a=np.array([[1,1,1],[1,1,1]])
print(a)
b=np.zeros((3,3))
print(b)
c=np.full((2,5),7)
print(c)



[[1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [15]:
#q2)
import numpy as np
ar=np.arange(0,4)
a=ar.reshape(2,2)
print("original aarray:\n",a)
cube=np.power(a,3)
print("cube is:",cube)
sum=a+7
print("sum of 7 is:",sum)
mul=a*2
print("mul of 2 is:",mul)


original aarray:
 [[0 1]
 [2 3]]
cube is: [[ 0  1]
 [ 8 27]]
sum of 7 is: [[ 7  8]
 [ 9 10]]
mul of 2 is: [[0 2]
 [4 6]]


In [17]:
#q3)
import numpy as np
x=np.arange(2,19,2)
y=x.reshape(3,3)
print(y)
a=np.arange(9,0,-1)
b=a.reshape(3,3)
print(b)
mul=np.multiply(y,b)
print(mul)
## or
d=y*b
print(d)




[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[18 32 42]
 [48 50 48]
 [42 32 18]]
[[18 32 42]
 [48 50 48]
 [42 32 18]]


In [7]:
#q4)

import numpy as np

# Create a 2x2 array
array = np.array([[1, 2], [3, 4]])

print("Original array:")
print(array)

# Swap the first row (no change since there are only two rows, but let's do it for consistency)
array[[0, 1]] = array[[1, 0]]

print("\nArray after swapping rows:")
print(array)

# Swap the first two columns
array[:, [0, 1]] = array[:, [1, 0]]

print("\nArray after swapping columns:")
print(array)



Original array:
[[1 2]
 [3 4]]

Array after swapping rows:
[[3 4]
 [1 2]]

Array after swapping columns:
[[4 3]
 [2 1]]


In [9]:
#q5)
import numpy as np

l1=[2,3,5,7,11]
l2=[13,17,19,23,29]
array=np.array([l1,l2])
array

array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29]])

In [41]:
#q6))
import numpy as np
a=np.array([[2**0,2**1,2**2],[2**3,2**4,2**5]])
b=a.flatten()
c=a.ravel()#in ravel if u modify some thing it will also grt modify in the orginal array ex- in a 
c[0]=99


print(a)
print(b)
print(c)
print(a)




[[99  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]
[99  2  4  8 16 32]
[[99  2  4]
 [ 8 16 32]]


In [125]:
#q7)
import numpy as np
from collections import Counter

# Example array
array = np.array(['s','d','s','d','s','d','d','d','d','s'])

# Count the frequency of each element
frequency = Counter(array)

# Find the most frequent value
most = frequency.most_common(1)[0][0]
print("Most frequent value:", most)


Most frequent value: d


In [15]:
#Q8)
import numpy as np
a=np.linspace(1.1,6.6,6)
b=a.reshape(2,3)
c=b.astype(int)
print(a)
print(b)
print(c)

[1.1 2.2 3.3 4.4 5.5 6.6]
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]


In [43]:
#q10)
import numpy as np

b=np.arange(1,16).reshape(3,5)

print(b,"\n\n")
print("row 2:",b[2],"\n\n")

print("column 5:",b[:, 4],"\n\n")
print("row 0 &1\n",b[0:2],"\n\n")
print("column 2-4",b[:, 2:5],"\n\n")
print("row 1&4",b[1,4],"\n\n")
print("row 1,2 columns 0,2,4:\n",b[1:3,0:5:2],"\n\n") #or another way
print("row 2,2 columns 1,2,3:\n",b[1:3,[1,2,3]],"\n\n")
      



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 


row 2: [11 12 13 14 15] 


column 5: [ 5 10 15] 


row 0 &1
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 


column 2-4 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]] 


row 1&4 10 


row 1,2 columns 0,2,4:
 [[ 6  8 10]
 [11 13 15]] 


row 2,2 columns 1,2,3:
 [[ 7  8  9]
 [12 13 14]] 




In [63]:
#q11)
import numpy as np

# Given arrays
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# (a) Vertical stacking
array3 = np.vstack((array1, array2))
print("array3:\n", array3)

# (b) Horizontal stacking
array4 = np.hstack((array1, array2))
print("\narray4:\n", array4)

# (c) Vertical stacking with two copies of array4
array5 = np.vstack((array4, array4))
print("\narray5:\n", array5)

# (d) Horizontal stacking with two copies of array3
array6 = np.hstack((array3, array3))
print("\narray6:\n", array6)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

array4:
 [[0 1 4 5]
 [2 3 6 7]]

array5:
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

array6:
 [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [65]:
#q12)
import numpy as np

# Given arrays
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# (a) Vertical stacking using concatenate
array3 = np.concatenate((array1, array2), axis=0)   #axis 0 means in row column by column then next row column by column ... in vertical way|
print("array3:\n", array3)                                                                                                                 

# (b) Horizontal stacking using concatenate
array4 = np.concatenate((array1, array2), axis=1) #axis 1 means in array1 st row &  in array2 1st row in horizontal 
print("\narray4:\n", array4)

# (c) Vertical stacking with two copies of array4 using concatenate
array5 = np.concatenate((array4, array4), axis=0)
print("\narray5:\n", array5)

# (d) Horizontal stacking with two copies of array3 using concatenate
array6 = np.concatenate((array3, array3), axis=1)
print("\narray6:\n", array6)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

array4:
 [[0 1 4 5]
 [2 3 6 7]]

array5:
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

array6:
 [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [71]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
# axis 0 (rows): [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# axis 1 (columns): [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
axis 0: refer to the direction along the row (vertically down the column)
axis 1:refer to the direction along the coluimn (horizontally across the row)


In [75]:
#q13)
import numpy as np

# Create a basic 2x2 pattern
a = np.array([['-', '*'], ['*', '-']])
print(a)

# Create a larger checkerboard pattern by tiling the basic pattern
checkerboard_pattern = np.tile(a, (4, 4))  # Adjust the (4, 4) to the desired size
                        #here tile is used to say how many times array is repeated in each direction here it is repeated 4 times in row & column
print(checkerboard_pattern)


[['-' '*']
 ['*' '-']]
[['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']]


In [79]:
#q14)
import numpy as np

# Create a 5x5 array of random integers in the range 0-99
array = np.random.randint(0, 100, size=(5, 5))

# Flatten the array to a 1D array
flattened_array = array.flatten()

# Use the bincount function to count the occurrences of each integer
counts = np.bincount(flattened_array)

# Print the array and the counts
print("Array:\n", array)
print("\nCounts:\n", counts)





Array:
 [[ 1 37 87 24 50]
 [53 23 42 34 47]
 [30 19 28  2 31]
 [47 61 42 48 68]
 [38 51 75 35 49]]

Counts:
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 0 1 1 0
 1 1 0 0 0 2 0 0 0 0 2 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 1]


In [121]:
#q15)
import numpy as np
a=np.array([1,2,3,4,4,3,3,3,3])
b=np.array([[1,2,3,4],[5,4,7,8]])
c=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[1,5,5,5]]])
print("a:",a)
print("median of a:",np.median(a))
print("mode of a:",stats.mode(a,axis=None))
print("b:\n",b)
print("median of b:",np.median(b))
print("mode of b:",stats.mode(b,axis=None))

print("c:\n",c)
print("median of b:",np.median(c))
print("mode of c:",stats.mode(c,axis=None))





a: [1 2 3 4 4 3 3 3 3]
median of a: 3.0
mode of a: ModeResult(mode=3, count=5)
b:
 [[1 2 3 4]
 [5 4 7 8]]
median of b: 4.0
mode of b: ModeResult(mode=4, count=2)
c:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 1  5  5  5]]]
median of b: 5.0
mode of c: ModeResult(mode=5, count=4)


In [133]:
#q16)
import numpy as np
a=np.random.rand(9,9,2)
print("a:",a)
print("subarray:",a[:5,:5,:])


a: [[[0.60640129 0.73662165]
  [0.03144347 0.54299847]
  [0.78515307 0.96079196]
  [0.50687107 0.19402891]
  [0.03029015 0.99098161]
  [0.04233352 0.12126428]
  [0.52068353 0.91350836]
  [0.83044519 0.83290699]
  [0.23576473 0.02081349]]

 [[0.03864169 0.63234388]
  [0.17756845 0.01218529]
  [0.8826934  0.04974238]
  [0.64756878 0.16895465]
  [0.55667346 0.6624502 ]
  [0.01708771 0.81515655]
  [0.55150994 0.36090043]
  [0.35889397 0.4327769 ]
  [0.77440907 0.55818099]]

 [[0.55343043 0.88376833]
  [0.80389641 0.74396423]
  [0.38665518 0.52472736]
  [0.11464883 0.17193511]
  [0.86513542 0.90351561]
  [0.90671561 0.10362905]
  [0.72107788 0.89446637]
  [0.17861498 0.61596401]
  [0.97803761 0.11729992]]

 [[0.55700243 0.44534873]
  [0.55349796 0.90095222]
  [0.35983686 0.27808801]
  [0.81128109 0.45579807]
  [0.06735487 0.37856187]
  [0.10847188 0.21055275]
  [0.88995974 0.00661052]
  [0.22609052 0.55546322]
  [0.67950467 0.3045793 ]]

 [[0.90006852 0.22400906]
  [0.27951733 0.4214876 ]
 

In [145]:
#q17)
import numpy as np
a=np.random.rand(4,4)
print(a)
b=np.sort(a,axis=0)
print(b)

[[0.28209421 0.86004332 0.67527539 0.86778593]
 [0.11060484 0.30294304 0.59040116 0.19283807]
 [0.58294628 0.36621493 0.92657008 0.67039754]
 [0.0727289  0.54403821 0.08891877 0.75137614]]
[[0.0727289  0.30294304 0.08891877 0.19283807]
 [0.11060484 0.36621493 0.59040116 0.67039754]
 [0.28209421 0.54403821 0.67527539 0.75137614]
 [0.58294628 0.86004332 0.92657008 0.86778593]]


In [55]:
#q18)
import pandas as pd
data={
    "c1":[1,2,3,4,5],
    "c2":[10,20,30,40,50],
    "c3":[100,200,300,400,500]
}
df=pd.DataFrame(data)

s=df.iloc[:,2]
print(df)
print(s)

    

   c1  c2   c3
0   1  10  100
1   2  20  200
2   3  30  300
3   4  40  400
4   5  50  500
0    100
1    200
2    300
3    400
4    500
Name: c3, dtype: int64


In [55]:
#q19)
import pandas as pd

# Lists
s1 = [1, 2, 3, 4, 2]
s2 = [3, 4, 5, 6]

# Convert lists to Pandas Series
series1 = pd.Series(s1)
series2 = pd.Series(s2)

print("Series 1:\n", series1)
print("\nSeries 2:\n", series2)

# Find elements in series1 not present in series2
unique_elements = series1[~series1.isin(series2)]
                         #series1.isin(series2) returns true is s1 is in s2
                  
print("\nElements in Series 1 not present in Series 2:\n", unique_elements)

Series 1:
 0    1
1    2
2    3
3    4
4    2
dtype: int64

Series 2:
 0    3
1    4
2    5
3    6
dtype: int64

Elements in Series 1 not present in Series 2:
 0    1
1    2
4    2
dtype: int64


In [53]:
#20)
import pandas as pd

a=[1,1,3,7,88,12,88,23,3,1,9,0]
s=pd.Series(a)
print(s)
idx_smlst=s.idxmin()
idx_bg=s.idxmax()
print("min index:",idx_smlst,"max index:",idx_bg)


0      1
1      1
2      3
3      7
4     88
5     12
6     88
7     23
8      3
9      1
10     9
11     0
dtype: int64
min index: 11 max index: 4


In [61]:
#q21)
import pandas as pd

# Convert the list to a Pandas Series
L = ['Cry', 'Apple', 'Orange', 'Sky', 'Banana']
series = pd.Series(L)

# Create a new Series with elements that have a vowel
vowel_series = series[series.str.contains('[AEIOUaeiou]')]

# Create another Series which starts with a vowel
starts_with_vowel_series = series[series.str.match('^[AEIOUaeiou]')]

print("Original Series:")
print(series)

print("\nSeries with elements that have a vowel:")
print(vowel_series)

print("\nSeries with elements that start with a vowel:")
print(starts_with_vowel_series)

Original Series:
0       Cry
1     Apple
2    Orange
3       Sky
4    Banana
dtype: object

Series with elements that have a vowel:
1     Apple
2    Orange
4    Banana
dtype: object

Series with elements that start with a vowel:
1     Apple
2    Orange
dtype: object


In [45]:

#22)import pandas as pd
import numpy as np
a=[7,11,13,17]
s=pd.Series(a)
print(s)
b=pd.Series([100]*5)
print(b)

c=pd.Series(np.random.randint(0,101,size=20))
print(c.describe())
print(c)

0     7
1    11
2    13
3    17
dtype: int64
0    100
1    100
2    100
3    100
4    100
dtype: int64
count    20.000000
mean     48.500000
std      30.586375
min       6.000000
25%      21.250000
50%      49.500000
75%      74.000000
max      97.000000
dtype: float64
0     19
1     97
2     18
3     74
4      6
5     56
6     90
7     74
8     62
9     45
10    87
11    54
12    25
13    22
14     8
15    27
16    39
17    88
18    70
19     9
dtype: int32


In [51]:
#continue 22)
temp=[98.6,98.9,100.2,97.9]
temperature=pd.Series(temp,index=["julice","charlie","sam","andrea"])
print(temperature)



julice      98.6
charlie     98.9
sam        100.2
andrea      97.9
dtype: float64


In [75]:
import random
s2=pd.Series([100]*5)
s3 = [random.randint(0, 100) for i in range(20)]
s4=pd.Series(s3)
s4


0     21
1     12
2     79
3     80
4     70
5      3
6     92
7     88
8     72
9     20
10    78
11    84
12    99
13     2
14    89
15    99
16    13
17     5
18    17
19    29
dtype: int64